version: '3.8'

services:
  selenium:
    image: selenium/standalone-firefox@sha256:4cee1e9d02dc0ff00683582a678a904991016a4534fa61bda2db11982d5094f4
    ports:
      - 4444:4444
    networks:
      - op-net

networks:
  op-net: