platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((readonly_private_ecr_repo_name))
    tag: di-toolbox-latest
    aws_access_key_id: ((readonly_access_key_id))
    aws_secret_access_key: ((readonly_secret_access_key))
    aws_session_token: ((readonly_session_token))
    aws_region: eu-west-2
inputs:
  - name: di-authentication-acceptance-tests
params:
  ENVIRONMENT_NAME: build
  DEPLOYER_ROLE_ARN: ((deployer-role-arn-non-prod))
  TEST_USER_EMAIL: ((test-user-email))
  TEST_USER_PASSWORD: ((test-user-password))
  TEST_USER_PHONE_NUMBER: ((test-user-phone-number))
  EMAIL_CODE_LOCK_TEST_USER_EMAIL: ((test-user-email-lock-email))
  PHONE_CODE_LOCK_TEST_USER_EMAIL: ((test-user-phone-lock-email))
  TEST_USER_NEW_EMAIL: ((test-user-new-email))
  TERMS_AND_CONDITIONS_TEST_USER_EMAIL: ((test-user-terms-and-conditions-email))
  TEST_USER_LATEST_TERMS_AND_CONDITIONS_VERSION: ((test-user-latest-terms-and-conditions))
  TEST_USER_AUTH_APP_EMAIL: ((test-user-auth-app-email))
  RESEND_CODE_TEST_USER_EMAIL: ((test-user-resend-email))
  IPN1_NEW_USER_EMAIL: ((test-user-new-email-ip1))
  IPN2_NEW_USER_EMAIL: ((test-user-new-email-ip2))
  IPN3_NEW_USER_EMAIL: ((test-user-new-email-ip3))
  IPN4_EXISTING_USER_EMAIL: ((test-user-email-ip4))
  IPN4_EXISTING_USER_PHONE: ((test-user-phone-number))
  RESET_PW_USER_EMAIL: ((test-user-reset-pw-email))
  REQ_RESET_PW_USER_EMAIL: ((test-user-req-reset-pw-email))
  TOP_100K_PASSWORD: ((test-user-req-reset-pw-password))
  ACCOUNT_RECOVERY_USER_AUTH_APP_SECRET: ((test-user-pw-reset-auth-app-secret))
  TEST_USER_ACCOUNT_RECOVERY_EMAIL_1: ((test-user-pw-reset-sms-email))
  TEST_USER_ACCOUNT_RECOVERY_EMAIL_2: ((test-user-pw-reset-auth-app-email))
  TEST_USER_ACCOUNT_RECOVERY_EMAIL_3: ((test-user-pw-not-reset-email))
  TEST_USER_ACCOUNT_RECOVERY_EMAIL_4: ((test-user-pw-not-reset-auth-app-email))
  PW_RESET_TEST_USER_PHONE: ((test-user-phone-number))
  SECTOR_HOST: https://identity.build.account.gov.uk
  TEST_USER_STATE_PRESERVATION_EMAIL1: ((test-user-state-preservation-email1))
  TEST_USER_STATE_PRESERVATION_EMAIL2: ((test-user-state-preservation-email2))
  INCORRECT_EMAIL_OTP_FOR_PW_RESET_EMAIL: ((test-user-incorrect-email-otp-pw-reset))
  TOO_MANY_EMAIL_OTP_REQUESTS_FOR_PW_RESET_EMAIL: ((test-user-too-many-email-otp-pw-reset))

run:
  path: /bin/bash
  args:
    - -c
    - |
      set -eu
      
      source di-authentication-acceptance-tests/scripts/database.sh
      source di-authentication-acceptance-tests/scripts/reset-test-users.sh
      
      export AWS_REGION=eu-west-2
      STS_TOKEN=$(aws sts assume-role --role-arn="${DEPLOYER_ROLE_ARN}" --role-session-name="truncate-test-data")
      export AWS_ACCESS_KEY_ID="$(echo ${STS_TOKEN} | jq -r .Credentials.AccessKeyId)"
      export AWS_SECRET_ACCESS_KEY="$(echo ${STS_TOKEN} | jq -r .Credentials.SecretAccessKey)"
      export AWS_SESSION_TOKEN="$(echo ${STS_TOKEN} | jq -r .Credentials.SessionToken)"
      
      resetTestUsers
